architecture_name: efficientnet_b0
betas: !!python/tuple
- 0.9
- 0.999
channels: 1
dropout_rate: 0.2
learning_rate: 0.0001
output_dim: 39
question_index_groups: []
scheduler_params: {}
test_time_dropout: true
timm_kwargs: {}
use_imagenet_weights: false
weight_decay: 0.05
