name: laura2_env
channels:
  - pytorch
  - conda-forge
  - defaults

dependencies:
  # Python
  - python=3.11

  # Núcleo científico (conda)
  - numpy<2
  - scipy
  - pandas
  - astropy
  - matplotlib
  - seaborn
  - h5py
  - scikit-learn

  # PyTorch (conda, versión CPU)
  - pytorch
  - cpuonly

  # Pip para lo demás
  - pip
  - pip:
      - pytorch-lightning
      - nflows